export type { Holder } from './api/projects';
export type { HolderKind, HolderTab } from './model/holder-tab';
export { useProjectRights, type ProjectRights } from './model/rights';
export { useHolderAddress } from './model/use-holder-address';
export { AttributesSection } from './ui/attributes-section';
export { CaseSection } from './ui/case-section';
export { CreateProject } from './ui/create-project';
export { CreateArea, AreaArchiving, EditArea } from './ui/area-dialogs';
export { AreaMenu, ProjectMenu } from './ui/holder-menu';
export { HOLDER_SCREEN, HolderScreen, type HolderTabLink } from './ui/holder-screen';
