"""projects and portfolios

Revision ID: ee156ee934e4
Revises: 7b1c40e9d5a2
Create Date: 2026-08-28 12:26:43.981074+00:00

Надочередной слой планирования: портфели, проекты, их участники и связь задачи с
проектом. Переноса данных нет — ни одной из этих сущностей до ревизии не существовало.

## Две таблицы, а не одна с признаком вида

Проект и портфель одинаковы по полям, и слить их в одну таблицу с колонкой `kind`
кажется экономией. Она обошлась бы дороже: задача ссылается **только на проект**,
портфель задач не содержит. С общей таблицей этот запрет пришлось бы держать проверкой
в сценарии вместо внешнего ключа, и первая же ошибка дала бы задачу, привязанную к
портфелю, — состояние, которого не должно существовать, но которое база разрешает.

## Прогресса в схеме нет, и это решение

Колонки «процент готовности» у проекта не появится. Задачу закрывают из REST, из MCP,
из автоматики и массовым переносом статуса, и каждое из этих мест обязано было бы
вспомнить про пересчёт — а забытое место дало бы цифру, расходящуюся с реальностью
молча. Прогресс считается запросом по `issues.project_id` и категории статуса; под него
и заведён индекс `ix_issues_project_id`.

## Самоссылка портфеля без каскада

`portfolios.parent_id` ссылается на ту же таблицу и объявлен без `ondelete`. Каскад,
уносящий вложенные портфели вместе с родителем, был бы катастрофой, к которой нет ни
одного сценария: портфели не удаляют, их архивируют.

Отсутствие цикла в этой ссылке внешним ключом не выражается — это свойство графа
целиком, а не строки. Проверку держит сценарий (`app/services/projects.py`), а читатели
защищены ограничителем глубины в рекурсивных запросах.

## `issues.project_id` — обычная nullable-колонка

Без `ondelete` по той же причине. `NULL` здесь — самое частое состояние: большинство
задач ни в один проект не входит, и это не недооформленность.

Из сгенерированной ревизии удалены строки `op.drop_constraint(... type_="check")` для
колонок-перечислений (`ck_actors_actor_type`, `ck_fields_field_value_type`,
`ck_issue_links_issue_link_type`, `ck_issues_issue_priority`,
`ck_outbox_events_outbox_status`, `ck_statuses_status_category`): автогенерация
приписывает их каждой ревизии, а оставленные — молча снимают проверку допустимых
значений (`docs/notes/db.md`).

Файл переименован из `20260828_1226_...`: предыдущая ревизия названа временем
`13:10`, взятым с часов, ушедших вперёд, и по имени новая ревизия оказалась бы выше
старой. Порядок наката это не меняет — его задаёт `down_revision`, — но каталог версий
должен читаться сверху вниз (`docs/notes/db.md`).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ee156ee934e4"
down_revision: str | None = "7b1c40e9d5a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolios",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "in_progress",
                "paused",
                "done",
                name="project_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default=sa.text("'not_started'"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["actors.id"], name=op.f("fk_portfolios_lead_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["portfolios.id"], name=op.f("fk_portfolios_parent_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
        sa.UniqueConstraint("key", name=op.f("uq_portfolios_key")),
    )
    op.create_index("ix_portfolios_created_at_id", "portfolios", ["created_at", "id"], unique=False)
    op.create_table(
        "portfolio_members",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
            name=op.f("fk_portfolio_members_actor_id_actors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_members_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_members")),
        sa.UniqueConstraint(
            "portfolio_id", "actor_id", name=op.f("uq_portfolio_members_portfolio_id_actor_id")
        ),
    )
    op.create_index(
        "ix_portfolio_members_actor_id", "portfolio_members", ["actor_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("portfolio_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "in_progress",
                "paused",
                "done",
                name="project_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default=sa.text("'not_started'"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["actors.id"], name=op.f("fk_projects_lead_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], name=op.f("fk_projects_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("key", name=op.f("uq_projects_key")),
    )
    op.create_index("ix_projects_created_at_id", "projects", ["created_at", "id"], unique=False)
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
            name=op.f("fk_project_members_actor_id_actors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_members_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_members")),
        sa.UniqueConstraint(
            "project_id", "actor_id", name=op.f("uq_project_members_project_id_actor_id")
        ),
    )
    op.create_index("ix_project_members_actor_id", "project_members", ["actor_id"], unique=False)
    op.add_column("issues", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.create_index("ix_issues_project_id", "issues", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_issues_project_id_projects"), "issues", "projects", ["project_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_issues_project_id_projects"), "issues", type_="foreignkey")
    op.drop_index("ix_issues_project_id", table_name="issues")
    op.drop_column("issues", "project_id")
    op.drop_index("ix_project_members_actor_id", table_name="project_members")
    op.drop_table("project_members")
    op.drop_index("ix_projects_created_at_id", table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_portfolio_members_actor_id", table_name="portfolio_members")
    op.drop_table("portfolio_members")
    op.drop_index("ix_portfolios_created_at_id", table_name="portfolios")
    op.drop_table("portfolios")
    # ### end Alembic commands ###
