"""notifications and subscriptions

Подписки на события и персональный инбокс актора.

Из сгенерированной ревизии **удалены** строки `op.drop_constraint(...)` по проверкам
`ck_*` у колонок-перечислений (акторы, автоматика, поля, связи, задачи, outbox, проекты,
портфели, спринты, статусы) и парные им `op.create_check_constraint` в `downgrade`.
Это известное ложное срабатывание автогенерации: имя ограничения, созданного
`string_enum`, вычисляется соглашением об именах только при компиляции DDL, и до этого
момента для сравнения оно «безымянное», то есть отсутствующее. Оставить их значило бы
молча снять с десяти колонок проверку допустимых значений — схема выглядела бы
правильной, а записать в них можно было бы любую строку. Подробности — в
`docs/notes/db.md`.

Revision ID: bc656a96d68b
Revises: d2e08534c9f9
Create Date: 2026-08-28 21:09:07.470822+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bc656a96d68b"
down_revision: str | None = "d2e08534c9f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_subscriptions",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "all",
                "queue",
                "project",
                "issue",
                "author",
                "assignee",
                "follower",
                "mention",
                "member",
                name="subscription_scope",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("scope_key", sa.String(length=128), nullable=True),
        sa.Column(
            "event_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "inbox",
                name="notification_channel",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default=sa.text("'inbox'"),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "notify_own_actions", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_notification_subscriptions_actor_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_subscriptions")),
        sa.UniqueConstraint(
            "actor_id",
            "scope",
            "scope_key",
            "channel",
            name="uq_notification_subscriptions_actor_id_scope_scope_key_channel",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_notification_subscriptions_actor_id_created_at_id",
        "notification_subscriptions",
        ["actor_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_subscriptions_scope_scope_key",
        "notification_subscriptions",
        ["scope", "scope_key"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_key", sa.String(length=128), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=True),
        sa.Column("issue_key", sa.String(length=128), nullable=True),
        sa.Column("digest_key", sa.String(length=193), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("count >= 1", name=op.f("ck_notifications_count_is_positive")),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_notifications_actor_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_notifications_issue_id_issues"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_actor_id_created_at_id",
        "notifications",
        ["actor_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_actor_id_created_at_id_unread",
        "notifications",
        ["actor_id", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("NOT is_read"),
    )
    op.create_index(
        "ix_notifications_actor_id_digest_key",
        "notifications",
        ["actor_id", "digest_key"],
        unique=False,
        postgresql_where=sa.text("NOT is_read"),
    )
    op.create_index("ix_notifications_issue_id", "notifications", ["issue_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_issue_id", table_name="notifications")
    op.drop_index(
        "ix_notifications_actor_id_digest_key",
        table_name="notifications",
        postgresql_where=sa.text("NOT is_read"),
    )
    op.drop_index(
        "ix_notifications_actor_id_created_at_id_unread",
        table_name="notifications",
        postgresql_where=sa.text("NOT is_read"),
    )
    op.drop_index("ix_notifications_actor_id_created_at_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "ix_notification_subscriptions_scope_scope_key", table_name="notification_subscriptions"
    )
    op.drop_index(
        "ix_notification_subscriptions_actor_id_created_at_id",
        table_name="notification_subscriptions",
    )
    op.drop_table("notification_subscriptions")
    # ### end Alembic commands ###
